/v1/users/me/transactions:
    get:
        tags:
            - transactions
        summary: Get the transactions history
        description: Get the transactions history
        produces:
            - application/json
        responses:
            200:
                description: OK
                schema:
                    type: object
                    required:
                        - transactions
                    properties:
                        divisions:
                            type: array
                            items:
                                type: object
                                required:
                                    - id
                                    - amount
                                    - type
                                    - effectiveDate
                                    - _links
                                properties:
                                    id:
                                        type: string
                                        example: 45745c60-7b1a-11e8-9c9c-2d42b21b1a3e
                                    amount:
                                        type: number
                                        example: 1000.00
                                    type:
                                        type: string
                                        example: debit
                                    effectiveDate:
                                        type: string
                                        format: date
                                    _links:
                                        type: object
                                        required:
                                            - self
                                        properties:
                                            self:
                                                type: object
                                                required:
                                                    - href
                                                properties:
                                                    href:
                                                        type: string
                                                        format: uri
                                                        example: http://localhost:8080/api/v1/users/me/transactions
            500:
                description: Internal server error
